/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as MessageAnalysisRouteImport } from './routes/message-analysis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkCheckRouteImport } from './routes/link-check'
import { Route as ExplainableRouteImport } from './routes/explainable'
import { Route as EducationRouteImport } from './routes/education'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertRouteImport } from './routes/alert'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransferAnalyzeRouteImport } from './routes/transfer.analyze'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageAnalysisRoute = MessageAnalysisRouteImport.update({
  id: '/message-analysis',
  path: '/message-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkCheckRoute = LinkCheckRouteImport.update({
  id: '/link-check',
  path: '/link-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainableRoute = ExplainableRouteImport.update({
  id: '/explainable',
  path: '/explainable',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertRoute = AlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferAnalyzeRoute = TransferAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => TransferRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alert': typeof AlertRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/education': typeof EducationRoute
  '/explainable': typeof ExplainableRoute
  '/link-check': typeof LinkCheckRoute
  '/login': typeof LoginRoute
  '/message-analysis': typeof MessageAnalysisRoute
  '/network': typeof NetworkRoute
  '/settings': typeof SettingsRoute
  '/transfer': typeof TransferRouteWithChildren
  '/twin': typeof TwinRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/transfer/analyze': typeof TransferAnalyzeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alert': typeof AlertRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/education': typeof EducationRoute
  '/explainable': typeof ExplainableRoute
  '/link-check': typeof LinkCheckRoute
  '/login': typeof LoginRoute
  '/message-analysis': typeof MessageAnalysisRoute
  '/network': typeof NetworkRoute
  '/settings': typeof SettingsRoute
  '/transfer': typeof TransferRouteWithChildren
  '/twin': typeof TwinRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/transfer/analyze': typeof TransferAnalyzeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alert': typeof AlertRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/education': typeof EducationRoute
  '/explainable': typeof ExplainableRoute
  '/link-check': typeof LinkCheckRoute
  '/login': typeof LoginRoute
  '/message-analysis': typeof MessageAnalysisRoute
  '/network': typeof NetworkRoute
  '/settings': typeof SettingsRoute
  '/transfer': typeof TransferRouteWithChildren
  '/twin': typeof TwinRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/transfer/analyze': typeof TransferAnalyzeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alert'
    | '/analytics'
    | '/audit'
    | '/dashboard'
    | '/demo'
    | '/education'
    | '/explainable'
    | '/link-check'
    | '/login'
    | '/message-analysis'
    | '/network'
    | '/settings'
    | '/transfer'
    | '/twin'
    | '/verify'
    | '/welcome'
    | '/transfer/analyze'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alert'
    | '/analytics'
    | '/audit'
    | '/dashboard'
    | '/demo'
    | '/education'
    | '/explainable'
    | '/link-check'
    | '/login'
    | '/message-analysis'
    | '/network'
    | '/settings'
    | '/transfer'
    | '/twin'
    | '/verify'
    | '/welcome'
    | '/transfer/analyze'
  id:
    | '__root__'
    | '/'
    | '/alert'
    | '/analytics'
    | '/audit'
    | '/dashboard'
    | '/demo'
    | '/education'
    | '/explainable'
    | '/link-check'
    | '/login'
    | '/message-analysis'
    | '/network'
    | '/settings'
    | '/transfer'
    | '/twin'
    | '/verify'
    | '/welcome'
    | '/transfer/analyze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertRoute: typeof AlertRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  EducationRoute: typeof EducationRoute
  ExplainableRoute: typeof ExplainableRoute
  LinkCheckRoute: typeof LinkCheckRoute
  LoginRoute: typeof LoginRoute
  MessageAnalysisRoute: typeof MessageAnalysisRoute
  NetworkRoute: typeof NetworkRoute
  SettingsRoute: typeof SettingsRoute
  TransferRoute: typeof TransferRouteWithChildren
  TwinRoute: typeof TwinRoute
  VerifyRoute: typeof VerifyRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message-analysis': {
      id: '/message-analysis'
      path: '/message-analysis'
      fullPath: '/message-analysis'
      preLoaderRoute: typeof MessageAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-check': {
      id: '/link-check'
      path: '/link-check'
      fullPath: '/link-check'
      preLoaderRoute: typeof LinkCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainable': {
      id: '/explainable'
      path: '/explainable'
      fullPath: '/explainable'
      preLoaderRoute: typeof ExplainableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert': {
      id: '/alert'
      path: '/alert'
      fullPath: '/alert'
      preLoaderRoute: typeof AlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer/analyze': {
      id: '/transfer/analyze'
      path: '/analyze'
      fullPath: '/transfer/analyze'
      preLoaderRoute: typeof TransferAnalyzeRouteImport
      parentRoute: typeof TransferRoute
    }
  }
}

interface TransferRouteChildren {
  TransferAnalyzeRoute: typeof TransferAnalyzeRoute
}

const TransferRouteChildren: TransferRouteChildren = {
  TransferAnalyzeRoute: TransferAnalyzeRoute,
}

const TransferRouteWithChildren = TransferRoute._addFileChildren(
  TransferRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertRoute: AlertRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  EducationRoute: EducationRoute,
  ExplainableRoute: ExplainableRoute,
  LinkCheckRoute: LinkCheckRoute,
  LoginRoute: LoginRoute,
  MessageAnalysisRoute: MessageAnalysisRoute,
  NetworkRoute: NetworkRoute,
  SettingsRoute: SettingsRoute,
  TransferRoute: TransferRouteWithChildren,
  TwinRoute: TwinRoute,
  VerifyRoute: VerifyRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
